// Portals
const BEFORE = 'before';
const AFTER = 'after';

export const GROUPED_PRODUCT = 'grouped-product';
export const GROUPED_PRODUCT_BEFORE = `${GROUPED_PRODUCT}.${BEFORE}`;
export const GROUPED_PRODUCT_AFTER = `${GROUPED_PRODUCT}.${AFTER}`;

export const GROUPED_PRODUCT_IMAGE = `${GROUPED_PRODUCT}.image`;
export const GROUPED_PRODUCT_IMAGE_BEFORE = `${GROUPED_PRODUCT}.image.${BEFORE}`;
export const GROUPED_PRODUCT_IMAGE_AFTER = `${GROUPED_PRODUCT}.image.${AFTER}`;

export const GROUPED_PRODUCT_META = `${GROUPED_PRODUCT}.meta`;
export const GROUPED_PRODUCT_META_BEFORE = `${GROUPED_PRODUCT}.meta.${BEFORE}`;
export const GROUPED_PRODUCT_META_AFTER = `${GROUPED_PRODUCT}.meta.${AFTER}`;

export const GROUPED_PRODUCT_PRICE = `${GROUPED_PRODUCT}.price`;
export const GROUPED_PRODUCT_PRICE_BEFORE = `${GROUPED_PRODUCT}.price.${BEFORE}`;
export const GROUPED_PRODUCT_PRICE_AFTER = `${GROUPED_PRODUCT}.price.${AFTER}`;

export const GROUPED_PRODUCT_NAME = `${GROUPED_PRODUCT}.name`;
export const GROUPED_PRODUCT_NAME_BEFORE = `${GROUPED_PRODUCT}.name.${BEFORE}`;
export const GROUPED_PRODUCT_NAME_AFTER = `${GROUPED_PRODUCT}.name.${AFTER}`;

export const GROUPED_PRODUCT_AVAILABILITY = `${GROUPED_PRODUCT}.availability`;
export const GROUPED_PRODUCT_AVAILABILITY_BEFORE = `${GROUPED_PRODUCT}.availability.${BEFORE}`;
export const GROUPED_PRODUCT_AVAILABILITY_AFTER = `${GROUPED_PRODUCT}.availability.${AFTER}`;

export const GROUPED_PRODUCT_CTA = `${GROUPED_PRODUCT}.cta`;
export const GROUPED_PRODUCT_CTA_BEFORE = `${GROUPED_PRODUCT}.cta.${BEFORE}`;
export const GROUPED_PRODUCT_CTA_AFTER = `${GROUPED_PRODUCT}.cta.${AFTER}`;

export const GROUPED_PRODUCT_ADD_TO_CART = `${GROUPED_PRODUCT}.add-to-cart`;
export const GROUPED_PRODUCT_ADD_TO_CART_BEFORE = `${GROUPED_PRODUCT}.add.${BEFORE}`;
export const GROUPED_PRODUCT_ADD_TO_CART_AFTER = `${GROUPED_PRODUCT}.add.${AFTER}`;

export const GROUPED_PRODUCT_FAVORITES = `${GROUPED_PRODUCT}.favorites`;
export const GROUPED_PRODUCT_FAVORITES_BEFORE = `${GROUPED_PRODUCT}.favorites.${BEFORE}`;
export const GROUPED_PRODUCT_FAVORITES_AFTER = `${GROUPED_PRODUCT}.favorites.${AFTER}`;
